package thecollector.model.mtg.card;

import java.util.ArrayList;

/**
 * A class to represent an MTG token.
 * 
 * Based on MTGJSON token structure 4.2.1
 * https://mtgjson.com/structures/token/
 * 
 * Changelog:
 * 24 Feb 2019 - Now using MTGJSON structures from 4.2.1.
 * 
 * @author Ian Claridge
 * 
 */
public class Token {
	private String artist;	// Name of artist e.g. "Jack Wang".
	private String borderColor; // Color of the border. Can be black, borderless, gold, silver, or white.
	private ArrayList<String> colorIdentity; // List of all colors in card’s mana e.g. ["G","W"].
	private ArrayList<String> colorIndicator; // List of all colors in card’s color indicator. Usually found only on cards without mana costs and other special cards.
	private ArrayList<String> colors; // List of all colors in card’s mana cost and any color indicator e.g. ["G","W"].
	private boolean isOnlineOnly; // Is the token only available online? Can be true or false. (If false, it is usually omitted.)
	private String loyalty; // Planeswalker loyalty value e.g. "7".
	private String name; // Name of the token e.g. "Elf Knight".
	private String number; // Number of the token card e.g. "2".
	private String power; // Power of the creature e.g. "2".
	private ArrayList<String> reverseRelated; // List of cards in the same set which reference the token e.g. ["Assemble","Conclave Cavalier","Conclave Guildmage","Sprouting Renewal"].
	private String scryfallId; // A universal unique id (v4) generated by Scryfall. Note that cards with multiple faces are not unique. E.g. "74506297-41ad-40e5-bb05-175650ff4907".
	private String side; // Identifier of the side. Used on cards with multiple faces, such as flip, split, transform cards. Can be a, b, or c.
	private String text; // Rules text of the token e.g. "Vigilance".
	private String toughness; // Toughness of the creature e.g. "4".
	private String type; // Type of the token. Includes any supertypes and subtypes. Will have either Token or Emblem listed as if a card type. E.g. "Token Creature — Elf Knight".
	private String uuid; // A universal unique id (v5) generated by MTGJSON. Each entry is unique. E.g. "b408de19-f203-502d-8325-28304ec21602".
	private String watermark; // Name of the watermark on the card. Can be one of many different values, including a guild name, clan name, or wotc for the shooting star. (If there isn’t one, it can be an empty string, but it is usually omitted.) E.g. "selesnya"
	
	public String getArtist() {
		return artist;
	}
	public void setArtist(String artist) {
		this.artist = artist;
	}
	public String getBorderColor() {
		return borderColor;
	}
	public void setBorderColor(String borderColor) {
		this.borderColor = borderColor;
	}
	public ArrayList<String> getColorIdentity() {
		return colorIdentity;
	}
	public void setColorIdentity(ArrayList<String> colorIdentity) {
		this.colorIdentity = colorIdentity;
	}
	public ArrayList<String> getColorIndicator() {
		return colorIndicator;
	}
	public void setColorIndicator(ArrayList<String> colorIndicator) {
		this.colorIndicator = colorIndicator;
	}
	public ArrayList<String> getColors() {
		return colors;
	}
	public void setColors(ArrayList<String> colors) {
		this.colors = colors;
	}
	public boolean isOnlineOnly() {
		return isOnlineOnly;
	}
	public void setOnlineOnly(boolean isOnlineOnly) {
		this.isOnlineOnly = isOnlineOnly;
	}
	public String getLoyalty() {
		return loyalty;
	}
	public void setLoyalty(String loyalty) {
		this.loyalty = loyalty;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getNumber() {
		return number;
	}
	public void setNumber(String number) {
		this.number = number;
	}
	public String getPower() {
		return power;
	}
	public void setPower(String power) {
		this.power = power;
	}
	public ArrayList<String> getReverseRelated() {
		return reverseRelated;
	}
	public void setReverseRelated(ArrayList<String> reverseRelated) {
		this.reverseRelated = reverseRelated;
	}
	public String getScryfallId() {
		return scryfallId;
	}
	public void setScryfallId(String scryfallId) {
		this.scryfallId = scryfallId;
	}
	public String getSide() {
		return side;
	}
	public void setSide(String side) {
		this.side = side;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getToughness() {
		return toughness;
	}
	public void setToughness(String toughness) {
		this.toughness = toughness;
	}
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
	public String getUuid() {
		return uuid;
	}
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}
	public String getWatermark() {
		return watermark;
	}
	public void setWatermark(String watermark) {
		this.watermark = watermark;
	}
}
